### ISSUE TITLE
[User story] Show news from lenta ru

### ISSUE THREAD

**Issue by programmerr47** [programmerr47/rss-simple-app#3]
As a user I want to enter in application and see progress bar. Then app need to show latest news from lenta.ru

Below will be tasks for that story:
- [x] #7 Choose xml parse lib
- [x] #9 Add request to lenta ru rss
- [x] #11 Add List Activity for displaying items
- [x] #12 Added progress bar to indicating progress

**Comment by programmerr47** [comment]
Done all items. Close it!
