### ISSUE TITLE
[User story] Additionally show news from gazeta ru

### ISSUE THREAD

**Issue by programmerr47** [programmerr47/rss-simple-app#4]
As a user I want to enter the application and see not only lenta's news but also gazeta's news. Both sorted by latest date.

Here is a list of tasks for that story:
- [x] #17 Make a success request to Gazeta rss using SimpleXML
- [x] #16 Create Merge Request (Merging Lenta news and Gazeta news)
- [x] #18 Display news from both sources (Lenta and Gazeta)
